
#服务提供者
spring:
  application:
    name: provider  #当前注册在职注册完中心的名字


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8001/eureka/  #注意要有空格 启动后直接访问http://localhost:8001/
    #是否将当前的服务提供者的Ip地址注册到eureka server中
  instance:
    prefer-ip-address: true
server:
  port: 8888



























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































