server:
  port: 8892
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true  #开启熔断机制