server:
  port: 8891
spring:
  application:
    name: ribbon
  instance:
    prefer-ip-address: true
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8001/eureka
  instance:
    prefer-ip-address: true
